language: cpp

build:
  compile_commands: compile_commands.json

tools:
  infer:
    enabled: true
    skip_files:
      - 'src/reactor.cpp'
      - 'src/reactor.h'
      - 'src/tests/test_reactor.cpp'
