---
engines:
  coverage:
    enabled: false

exclude_paths:
  - 'data/raids/dragonsMountainSpawn.xml'
  - 'data/scripts/stress_db.lua'
  - 'data/scripts/testclientevent.lua'
  - 'vcpkg_installed/**'
  - 'build-release/**'
  - 'build/**'
  - 'build-asan*/**'
